[package]
name = "survival"
version = "0.1.0"
edition = "2024"

[lib]
name = "survival"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
ndarray = "0.17.1"
numpy = "0.27.1"
ndarray-linalg = "0.18.0"
itertools = "0.14.0"
